import { StyleSheet } from "react-native"; 

export const style = StyleSheet.create({ 
       container: { 
    flex: 1, 
    backgroundColor: "#000000ff", 
  }, 
  content: {
    flex: 1,
    marginTop: 5, // Ajuste conforme necessário
  },
    textContainer: {
    marginTop: 10,
  },
  productTitle: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "left",
    color: "#ffffffff",
      paddingHorizontal: 5,
  },
  BotaoRedondo :{
   flexDirection: "row",
  },
  botoesAcaoContainer: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  gap: 10,
  marginVertical: 15,
  paddingHorizontal: 10,
},
BotaoCarrinho: {
  flex: 1,
  padding: 15,
  borderRadius: 8,
  alignItems: 'center',
  justifyContent: 'center',
  minHeight: 50,
},
  BotaoDestaque:{
  paddingHorizontal: 10,
  backgroundColor: 'gray',
  borderRadius: 16,
  color: 'white',
  fontSize: 16,
  fontWeight: "bold",
  marginTop: 15,
  marginHorizontal: 5,
  },
  BotaoNovidade: {
  paddingHorizontal: 10,
  backgroundColor: 'white',
  borderRadius: 16,
  color: 'black',
  fontSize: 16,
  fontWeight: "bold",
  marginTop: 15,
  marginHorizontal: 5,
  },
  BotaoDuvidas: {
  paddingHorizontal: 10,
  backgroundColor: 'gray',
  borderRadius: 16,
  color: 'white',
  fontSize: 16,
  marginTop: 15,
  marginHorizontal: 25,
  alignItems: 'center',
  textAlign: 'center',
  },
   productpreço: {
    marginTop: 18,
    fontSize: 36,
    fontWeight: "bold",
    textAlign: "left",
    color: "#ffffffff",
      paddingHorizontal: 5,
  },
  descriçaoPreco:{
    marginTop: 5,
    fontSize: 12,
    textAlign: "left",
    color: "#ffffffff",
       paddingHorizontal: 5,
  },
  
input: {
    width: "15%",
    height: 50,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    color: "#fff",
    fontSize: 16,
  },
  input1: {
    width: "25%",
    height: 50,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 25,
    color: "#fff",
    fontSize: 16,
  },
  cep: {
    color: "#fff",
    fontSize: 26,
    marginRight: 10,
    marginTop: 5,
  },
  cep12: {
    color: "#fff",
    fontSize: 26,
    marginRight: 10,
    marginLeft: 10,
    marginTop: 5,
  },
  entrega: {
    color: "#fff",
    fontSize: 16,
    marginLeft: 5,
    marginBottom: 20,
  },
   produtoContainer: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    marginHorizontal: 15,
    marginBottom: 20,
    padding: 15,
    flexDirection: 'row',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  imagemContainer: {
    marginRight: 15,
  },
  imagemProduto: {
    width: 120,
    height: 120,
    borderRadius: 8,
  },
  infoContainer: {
    flex: 1,
    justifyContent: 'space-between',
  },
  tituloProduto: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    lineHeight: 20,
    marginBottom: 8,
  },
  precoPrincipal: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 6,
  },
  precoParcelado: {
    fontSize: 12,
    color: '#cccccc',
    lineHeight: 16,
    marginBottom: 12,
  },
  botaoEscolher: {
    backgroundColor: '#ffffff',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  textoBotao: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000000',
  },
  tituloOutrosProdutos: {
    fontSize: 24,
    color: 'white',
    marginLeft: 15,
    marginTop: 30, // Aumente este valor
    marginBottom: 20,
    fontWeight: "bold",
},
}); 